package types.gen1;

public class Data {
    static final String[] encodingTable = {
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", " ", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M",
            "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "(", ")",
            ":", ";", "[", "]", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k",
            "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "",
            "'", "", "", "-", "", "", "?", "!", ".", "", "", "", "", "", "", "",
            "", "", ".", "/", ",", "", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9"
    };
    static String[] items = {
           "~0",
           "Master Ball",
           "Ultra Ball",
           "Great Ball",
           "Poke Ball",
           "Town Map",
           "Bicycle",
           "?????",
           "Safari Ball",
           "Pokedex",
           "Moon Stone",
           "Antidote",
           "Burn Heal",
           "Ice Heal",
           "Awakening",
           "Parlyz Heal",
           "Full Restore",
           "Max Potion",
           "Hyper Potion",
           "Super Potion",
           "Potion",
           "Boulderbadge",
           "Cascadebadge",
           "Thunderbadge",
           "Rainbowbadge",
           "Soulbadge",
           "Marshbadge",
           "Volcanobadge",
           "Earthbadge",
           "Escape Rope",
           "Repel",
           "Old Amber",
           "Fire Stone",
           "Thunderstone",
           "Water Stone",
           "HP Up",
           "Protein",
           "Iron",
           "Carbos",
           "Calcium",
           "Rare Candy",
           "Dome Fossil",
           "Helix Fossil",
           "Secret Key",
           "?????",
           "Bike Voucher",
           "X Accuracy",
           "Leaf Stone",
           "Card Key",
           "Nugget",
           "PP Up",
           "Poke Doll",
           "Full Heal",
           "Revive",
           "Max Revive",
           "Guard Spec",
           "Super Repel",
           "Max Repel",
           "Dire Hit",
           "Coin",
           "Fresh Water",
           "Soda Pop",
           "Lemonade",
           "S.S.Ticket",
           "Gold Teeth",
           "X Attack",
           "X Defend",
           "X Speed",
           "X Special",
           "Coin Case",
           "Oak Parcel",
           "Itemfinder",
           "Silph Scope",
           "Poke Flute",
           "Lift Key",
           "Exp.All",
           "Old Rod",
           "Good Rod",
           "Super Rod",
           "Pp Up",
           "Ether",
           "Max Ether",
           "Elixer",
           "Max Elixer",
           "~84",
           "~85",
           "~86",
           "~87",
           "~88",
           "~89",
           "~90",
           "~91",
           "~92",
           "~93",
           "~94",
           "~95",
           "~96",
           "~97",
           "~98",
           "~99",
           "~100",
           "~101",
           "~102",
           "~103",
           "~104",
           "~105",
           "~106",
           "~107",
           "~108",
           "~109",
           "~110",
           "~111",
           "~112",
           "~113",
           "~163",
           "~115",
           "~116",
           "~117",
           "~118",
           "~119",
           "~120",
           "~121",
           "~122",
           "~123",
           "~124",
           "~125",
           "~126",
           "~127",
           "~128",
           "~129",
           "~130",
           "~131",
           "~132",
           "~133",
           "~134",
           "~135",
           "~136",
           "~137",
           "~138",
           "~139",
           "~140",
           "~141",
           "~142",
           "~143",
           "~144",
           "~145",
           "~146",
           "~147",
           "~148",
           "~149",
           "~150",
           "~151",
           "~152",
           "~153",
           "~154",
           "~155",
           "~156",
           "~163",
           "~158",
           "~159",
           "~160",
           "~161",
           "~162",
           "~163",
           "~164",
           "~165",
           "~166",
           "~167",
           "~168",
           "~169",
           "~170",
           "~171",
           "~172",
           "~173",
           "~174",
           "~175",
           "~176",
           "~177",
           "~178",
           "~179",
           "~180",
           "~181",
           "~182",
           "~183",
           "~184",
           "~185",
           "~186",
           "~187",
           "~188",
           "~189",
           "~190",
           "~191",
           "~192",
           "~193",
           "~194",
           "~195",
           "HM01",
           "HM02",
           "HM03",
           "HM04",
           "HM05",
           "TM01",
           "TM02",
           "TM03",
           "TM04",
           "TM05",
           "TM06",
           "TM07",
           "TM08",
           "TM09",
           "TM10",
           "TM11",
           "TM12",
           "TM13",
           "TM14",
           "TM15",
           "TM16",
           "TM17",
           "TM18",
           "TM19",
           "TM20",
           "TM21",
           "TM22",
           "TM23",
           "TM24",
           "TM25",
           "TM26",
           "TM27",
           "TM28",
           "TM29",
           "TM30",
           "TM31",
           "TM32",
           "TM33",
           "TM34",
           "TM35",
           "TM36",
           "TM37",
           "TM38",
           "TM39",
           "TM40",
           "TM41",
           "TM42",
           "TM43",
           "TM44",
           "TM45",
           "TM46",
           "TM47",
           "TM48",
           "TM49",
           "TM50",
           "TM51",
           "TM52",
           "TM53",
           "TM54",
           "Nothing"
    };
    static String[] pokemons = {
           "~0",
           "Rhydon",
           "Kangaskhan",
           "Nidoranm",
           "Clefairy",
           "Spearow",
           "Voltorb",
           "Nidoking",
           "Slowbro",
           "Ivysaur",
           "Exeggutor",
           "Lickitung",
           "Exeggcute",
           "Grimer",
           "Gengar",
           "Nidoranh",
           "Nidoqueen",
           "Cubone",
           "Rhyhorn",
           "Lapras",
           "Arcanine",
           "Mew",
           "Gyarados",
           "Shellder",
           "Tentacool",
           "Gastly",
           "Scyther",
           "Staryu",
           "Blastoise",
           "Pinsir",
           "Tangela",
           "Missingno",
           "Missingno",
           "Growlithe",
           "Onix",
           "Fearow",
           "Pidgey",
           "Slowpoke",
           "Kadabra",
           "Graveler",
           "Chansey",
           "Machoke",
           "Mr.Mime",
           "Hitmonlee",
           "Hitmonchan",
           "Arbok",
           "Parasect",
           "Psyduck",
           "Drowzee",
           "Golem",
           "Missingno",
           "Magmar",
           "Missingno",
           "Electabuzz",
           "Magneton",
           "Koffing",
           "Missingno",
           "Mankey",
           "Seel",
           "Diglett",
           "Tauros",
           "Missingno",
           "Missingno",
           "Missingno",
           "Farfetch'",
           "Venonat",
           "Dragonite",
           "Missingno",
           "Missingno",
           "Missingno",
           "Doduo",
           "Poliwag",
           "Jynx",
           "Moltres",
           "Articuno",
           "Zapdos",
           "Ditto",
           "Meowth",
           "Krabby",
           "Missingno",
           "Missingno",
           "Missingno",
           "Vulpix",
           "Ninetales",
           "Pikachu",
           "Raichu",
           "Missingno",
           "Missingno",
           "Dratini",
           "Dragonair",
           "Kabuto",
           "Kabutops",
           "Horsea",
           "Seadra",
           "Missingno",
           "Missingno",
           "Sandshrew",
           "Sandslash",
           "Omanyte",
           "Omastar",
           "Jigglypuff",
           "Wigglytuff",
           "Eevee",
           "Flareon",
           "Jolteon",
           "Vaporeon",
           "Machop",
           "Zubat",
           "Ekans",
           "Paras",
           "Poliwhirl",
           "Poliwrath",
           "Weedle",
           "Kakuna",
           "Beedrill",
           "Missingno",
           "Dodrio",
           "Primeape",
           "Dugtrio",
           "Venomoth",
           "Dewgong",
           "Missingno",
           "Missingno",
           "Caterpie",
           "Metapod",
           "Butterfree",
           "Machamp",
           "Missingno",
           "Golduck",
           "Hypno",
           "Golbat",
           "Mewtwo",
           "Snorlax",
           "Magikarp",
           "Missingno",
           "Missingno",
           "Muk",
           "Missingno",
           "Kingler",
           "Cloyster",
           "Missingno",
           "Electrode",
           "Clefable",
           "Weezing",
           "Persian",
           "Marowak",
           "Missingno",
           "Haunter",
           "Abra",
           "Alakazam",
           "Pidgeotto",
           "Pidgeot",
           "Starmie",
           "Bulbasaur",
           "Venusaur",
           "Tentacruel",
           "Missingno",
           "Goldeen",
           "Seaking",
           "Missingno",
           "Missingno",
           "Missingno",
           "Missingno",
           "Ponyta",
           "Rapidash",
           "Rattata",
           "Raticate",
           "Nidorino",
           "Nidorina",
           "Geodude",
           "Porygon",
           "Aerodactyl",
           "Missingno",
           "Magnemite",
           "Missingno",
           "Missingno",
           "Charmander",
           "Squirtle",
           "Charmeleon",
           "Wartortle",
           "Charizard",
           "Missingno",
           "Missingno",
           "Missingno",
           "Missingno",
           "Oddish",
           "Gloom",
           "Vileplume",
           "Bellsprout",
           "Weepinbell",
           "Victreebel",
           "~191",
           "~192",
           "~193",
           "~194",
           "~195",
           "~196",
           "~197",
           "~198",
           "~199",
           "~200",
           "~201",
           "~202",
           "~203",
           "~204",
           "~205",
           "~206",
           "~207",
           "~208",
           "~209",
           "~210",
           "~211",
           "~212",
           "~213",
           "~214",
           "~215",
           "~216",
           "~217",
           "~218",
           "~219",
           "~220",
           "~221",
           "~222",
           "~223",
           "~224",
           "~225",
           "~226",
           "~227",
           "~228",
           "~229",
           "~230",
           "~231",
           "~232",
           "~233",
           "~234",
           "~235",
           "~236",
           "~237",
           "~238",
           "~239",
           "~240",
           "~241",
           "~242",
           "~243",
           "~244",
           "~245",
           "~246",
           "~247",
           "~248",
           "~249",
           "~250",
           "~251",
           "~252",
           "~253",
           "~254",
           "Empty"
    };
    static String[] pokedex = {
           "#000 Missingno",
           "#001 Bulbasaur",
           "#002 Ivysaur",
           "#003 Venusaur",
           "#004 Charmander",
           "#005 Charmeleon",
           "#006 Charizard",
           "#007 Squirtle",
           "#008 Wartortle",
           "#009 Blastoise",
           "#010 Caterpie",
           "#011 Metapod",
           "#012 Butterfree",
           "#013 Weedle",
           "#014 Kakuna",
           "#015 Beedrill",
           "#016 Pidgey",
           "#017 Pidgeotto",
           "#018 Pidgeot",
           "#019 Rattata",
           "#020 Raticate",
           "#021 Spearow",
           "#022 Fearow",
           "#023 Ekans",
           "#024 Arbok",
           "#025 Pikachu",
           "#026 Raichu",
           "#027 Sandshrew",
           "#028 Sandslash",
           "#029 Nidoranh",
           "#030 Nidorina",
           "#031 Nidoqueen",
           "#032 Nidoranm",
           "#033 Nidorino",
           "#034 Nidoking",
           "#035 Clefairy",
           "#036 Clefable",
           "#037 Vulpix",
           "#038 Ninetales",
           "#039 Jigglypuff",
           "#040 Wigglytuff",
           "#041 Zubat",
           "#042 Golbat",
           "#043 Oddish",
           "#044 Gloom",
           "#045 Vileplume",
           "#046 Paras",
           "#047 Parasect",
           "#048 Venonat",
           "#049 Venomoth",
           "#050 Diglett",
           "#051 Dugtrio",
           "#052 Meowth",
           "#053 Persian",
           "#054 Psyduck",
           "#055 Golduck",
           "#056 Mankey",
           "#057 Primeape",
           "#058 Growlithe",
           "#059 Arcanine",
           "#060 Poliwag",
           "#061 Poliwhirl",
           "#062 Poliwrath",
           "#063 Abra",
           "#064 Kadabra",
           "#065 Alakazam",
           "#066 Machop",
           "#067 Machoke",
           "#068 Machamp",
           "#069 Bellsprout",
           "#070 Weepinbell",
           "#071 Victreebel",
           "#072 Tentacool",
           "#073 Tentacruel",
           "#074 Geodude",
           "#075 Graveler",
           "#076 Golem",
           "#077 Ponyta",
           "#078 Rapidash",
           "#079 Slowpoke",
           "#080 Slowbro",
           "#081 Magnemite",
           "#082 Magneton",
           "#083 Farfetch'd",
           "#084 Doduo",
           "#085 Dodrio",
           "#086 Seel",
           "#087 Dewgong",
           "#088 Grimer",
           "#089 Muk",
           "#090 Shellder",
           "#091 Cloyster",
           "#092 Gastly",
           "#093 Haunter",
           "#094 Gengar",
           "#095 Onix",
           "#096 Drowzee",
           "#097 Hypno",
           "#098 Krabby",
           "#099 Kingler",
           "#100 Voltorb",
           "#101 Electrode",
           "#102 Exeggcute",
           "#103 Exeggutor",
           "#104 Cubone",
           "#105 Marowak",
           "#106 Hitmonlee",
           "#107 Hitmonchan",
           "#108 Lickitung",
           "#109 Koffing",
           "#110 Weezing",
           "#111 Rhyhorn",
           "#112 Rhydon",
           "#113 Chansey",
           "#163 Tangela",
           "#115 Kangaskhan",
           "#116 Horsea",
           "#117 Seadra",
           "#118 Goldeen",
           "#119 Seaking",
           "#120 Staryu",
           "#121 Starmie",
           "#122 Mr.Mime",
           "#123 Scyther",
           "#124 Jynx",
           "#125 Electabuzz",
           "#126 Magmar",
           "#127 Pinsir",
           "#128 Tauros",
           "#129 Magikarp",
           "#130 Gyarados",
           "#131 Lapras",
           "#132 Ditto",
           "#133 Eevee",
           "#134 Vaporeon",
           "#135 Jolteon",
           "#136 Flareon",
           "#137 Porygon",
           "#138 Omanyte",
           "#139 Omastar",
           "#140 Kabuto",
           "#141 Kabutops",
           "#142 Aerodactyl",
           "#143 Snorlax",
           "#144 Articuno",
           "#145 Zapdos",
           "#146 Moltres",
           "#147 Dratini",
           "#148 Dragonair",
           "#149 Dragonite",
           "#150 Mewtwo",
           "#151 Mew",
           "#152",
           "#153",
           "#154",
           "#155",
           "#156",
           "#163",
           "#158",
           "#159",
           "#160",
           "#161",
           "#162",
           "#163",
           "#164",
           "#165",
           "#166",
           "#167",
           "#168",
           "#169",
           "#170",
           "#171",
           "#172",
           "#173",
           "#174",
           "#175",
           "#176",
           "#177",
           "#178",
           "#179",
           "#180",
           "#181",
           "#182",
           "#183",
           "#184",
           "#185",
           "#186",
           "#187",
           "#188",
           "#189",
           "#190",
           "#191",
           "#192",
           "#193",
           "#194",
           "#195",
           "#196",
           "#197",
           "#198",
           "#199",
           "#200",
           "#201",
           "#202",
           "#203",
           "#204",
           "#205",
           "#206",
           "#207",
           "#208",
           "#209",
           "#210",
           "#211",
           "#212",
           "#213",
           "#214",
           "#215",
           "#216",
           "#217",
           "#218",
           "#219",
           "#220",
           "#221",
           "#222",
           "#223",
           "#224",
           "#225",
           "#226",
           "#227",
           "#228",
           "#229",
           "#230",
           "#231",
           "#232",
           "#233",
           "#234",
           "#235",
           "#236",
           "#237",
           "#238",
           "#239",
           "#240",
           "#241",
           "#242",
           "#243",
           "#244",
           "#245",
           "#246",
           "#247",
           "#248",
           "#249",
           "#250",
           "#251",
           "#252",
           "#253",
           "#254",
           "#255"
    };
    static String[] moves = {
           "No move",
           "Pound",
           "Karate Chop",
           "Doubleslap",
           "Comet Punch",
           "Mega Punch",
           "Pay Day",
           "Fire Punch",
           "Ice Punch",
           "Thunderpunch",
           "Scratch",
           "Vicegrip",
           "Guillotine",
           "Razor Wind",
           "Swords Dance",
           "Cut",
           "Gust",
           "Wing Attack",
           "Whirlwind",
           "Fly",
           "Bind",
           "Slam",
           "Vine Whip",
           "Stomp",
           "Double Kick",
           "Mega Kick",
           "Jump Kick",
           "Rolling Kick",
           "Sand-attack",
           "Headbutt",
           "Horn Attack",
           "Fury Attack",
           "Horn Drill",
           "Tackle",
           "Body Slam",
           "Wrap",
           "Take Down",
           "Thrash",
           "Double-edge",
           "Tail Whip",
           "Poison Sting",
           "Twineedle",
           "Pin Missile",
           "Leer",
           "Bite",
           "Growl",
           "Roar",
           "Sing",
           "Supersonic",
           "Sonicboom",
           "Disable",
           "Acid",
           "Ember",
           "Flamethrower",
           "Mist",
           "Water Gun",
           "Hydro Pump",
           "Surf",
           "Ice Beam",
           "Blizzard",
           "Psybeam",
           "Bubblebeam",
           "Aurora Beam",
           "Hyper Beam",
           "Peck",
           "Drill Peck",
           "Submission",
           "Low Kick",
           "Counter",
           "Seismic Toss",
           "Strength",
           "Absorb",
           "Mega Drain",
           "Leech Seed",
           "Growth",
           "Razor Leaf",
           "Solarbeam",
           "Poisonpowder",
           "Stun Spore",
           "Sleep Powder",
           "Petal Dance",
           "String Shot",
           "Dragon Rage",
           "Fire Spin",
           "Thundershock",
           "Thunderbolt",
           "Thunder Wave",
           "Thunder",
           "Rock Throw",
           "Earthquake",
           "Fissure",
           "Dig",
           "Toxic",
           "Confusion",
           "Psychic",
           "Hypnosis",
           "Meditate",
           "Agility",
           "Quick Attack",
           "Rage",
           "Teleport",
           "Night Shade",
           "Mimic",
           "Screech",
           "Double Team",
           "Recover",
           "Harden",
           "Minimize",
           "Smokescreen",
           "Confuse Ray",
           "Withdraw",
           "Defense Curl",
           "Barrier",
           "Light Screen",
           "Haze",
           "Reflect",
           "Focus Energy",
           "Bide",
           "Metronome",
           "Mirror Move",
           "Selfdestruct",
           "Egg Bomb",
           "Lick",
           "Smog",
           "Sludge",
           "Bone Club",
           "Fire Blast",
           "Waterfall",
           "Clamp",
           "Swift",
           "Skull Bash",
           "Spike Cannon",
           "Constrict",
           "Amnesia",
           "Kinesis",
           "Softboiled",
           "Hi Jump Kick",
           "Glare",
           "Dream Eater",
           "Poison Gas",
           "Barrage",
           "Leech Life",
           "Lovely Kiss",
           "Sky Attack",
           "Transform",
           "Bubble",
           "Dizzy Punch",
           "Spore",
           "Flash",
           "Psywave",
           "Splash",
           "Acid Armor",
           "Crabhammer",
           "Explosion",
           "Fury Swipes",
           "Bonemerang",
           "Rest",
           "Rock Slide",
           "Hyper Fang",
           "Sharpen",
           "Conversion",
           "Tri Attack",
           "Super Fang",
           "Slash",
           "Substitute",
           "Struggle",
           "~166",
           "~167",
           "~168",
           "~169",
           "~170",
           "~171",
           "~172",
           "~173",
           "~174",
           "~175",
           "~176",
           "~177",
           "~178",
           "~179",
           "~180",
           "~181",
           "~182",
           "~183",
           "~184",
           "~185",
           "~186",
           "~187",
           "~188",
           "~189",
           "~190",
           "~191",
           "~192",
           "~193",
           "~194",
           "~195",
           "~196",
           "~197",
           "~198",
           "~199",
           "~200",
           "~201",
           "~202",
           "~203",
           "~204",
           "~205",
           "~206",
           "~207",
           "~208",
           "~209",
           "~210",
           "~211",
           "~212",
           "~213",
           "~214",
           "~215",
           "~216",
           "~217",
           "~218",
           "~219",
           "~220",
           "~221",
           "~222",
           "~223",
           "~224",
           "~225",
           "~226",
           "~227",
           "~228",
           "~229",
           "~230",
           "~231",
           "~232",
           "~233",
           "~234",
           "~235",
           "~236",
           "~237",
           "~238",
           "~239",
           "~240",
           "~241",
           "~242",
           "~243",
           "~244",
           "~245",
           "~246",
           "~247",
           "~248",
           "~249",
           "~250",
           "~251",
           "~252",
           "~253",
           "~254",
           "~255"
    };
    static String[] types = {
           "Normal",
           "Fighting",
           "Flying",
           "Poison",
           "Ground",
           "Rock",
           "Bird",
           "Bug",
           "Ghost",
           "~9",
           "~10",
           "~11",
           "~12",
           "~13",
           "~14",
           "~15",
           "~16",
           "~17",
           "~18",
           "~19",
           "Fire",
           "Water",
           "Grass",
           "Electric",
           "Psychic",
           "Ice",
           "Dragon",
           "~27",
           "~28",
           "~29",
           "~30",
           "~31",
           "~32",
           "~33",
           "~34",
           "~35",
           "~36",
           "~37",
           "~38",
           "~39",
           "~40",
           "~41",
           "~42",
           "~43",
           "~44",
           "~45",
           "~46",
           "~47",
           "~48",
           "~49",
           "~50",
           "~51",
           "~52",
           "~53",
           "~54",
           "~55",
           "~56",
           "~57",
           "~58",
           "~59",
           "~60",
           "~61",
           "~62",
           "~63",
           "~64",
           "~65",
           "~66",
           "~67",
           "~68",
           "~69",
           "~70",
           "~71",
           "~72",
           "~73",
           "~74",
           "~75",
           "~76",
           "~77",
           "~78",
           "~79",
           "~80",
           "~81",
           "~82",
           "~83",
           "~84",
           "~85",
           "~86",
           "~87",
           "~88",
           "~89",
           "~90",
           "~91",
           "~92",
           "~93",
           "~94",
           "~95",
           "~96",
           "~97",
           "~98",
           "~99",
           "~100",
           "~101",
           "~102",
           "~103",
           "~104",
           "~105",
           "~106",
           "~107",
           "~108",
           "~109",
           "~110",
           "~111",
           "~112",
           "~113",
           "~163",
           "~115",
           "~116",
           "~117",
           "~118",
           "~119",
           "~120",
           "~121",
           "~122",
           "~123",
           "~124",
           "~125",
           "~126",
           "~127",
           "~128",
           "~129",
           "~130",
           "~131",
           "~132",
           "~133",
           "~134",
           "~135",
           "~136",
           "~137",
           "~138",
           "~139",
           "~140",
           "~141",
           "~142",
           "~143",
           "~144",
           "~145",
           "~146",
           "~147",
           "~148",
           "~149",
           "~150",
           "~151",
           "~152",
           "~153",
           "~154",
           "~155",
           "~156",
           "~163",
           "~158",
           "~159",
           "~160",
           "~161",
           "~162",
           "~163",
           "~164",
           "~165",
           "~166",
           "~167",
           "~168",
           "~169",
           "~170",
           "~171",
           "~172",
           "~173",
           "~174",
           "~175",
           "~176",
           "~177",
           "~178",
           "~179",
           "~180",
           "~181",
           "~182",
           "~183",
           "~184",
           "~185",
           "~186",
           "~187",
           "~188",
           "~189",
           "~190",
           "~191",
           "~192",
           "~193",
           "~194",
           "~195",
           "~196",
           "~197",
           "~198",
           "~199",
           "~200",
           "~201",
           "~202",
           "~203",
           "~204",
           "~205",
           "~206",
           "~207",
           "~208",
           "~209",
           "~210",
           "~211",
           "~212",
           "~213",
           "~214",
           "~215",
           "~216",
           "~217",
           "~218",
           "~219",
           "~220",
           "~221",
           "~222",
           "~223",
           "~224",
           "~225",
           "~226",
           "~227",
           "~228",
           "~229",
           "~230",
           "~231",
           "~232",
           "~233",
           "~234",
           "~235",
           "~236",
           "~237",
           "~238",
           "~239",
           "~240",
           "~241",
           "~242",
           "~243",
           "~244",
           "~245",
           "~246",
           "~247",
           "~248",
           "~249",
           "~250",
           "~251",
           "~252",
           "~253",
           "~254",
           "~255"
    };
}
